#!/bin/sh

# setup env
export LD_LIBRARY_PATH="/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/"
export PATH="$PATH:/opt/CrowdStrike/"

# link all applets
for app in `busybox --list`; do busybox ln -fs /bin/busybox /bin/$app; done

# mount virtual filesystems, proc required for sensor bridge
mount -t proc proc /proc
mount -t devtmpfs devtmpfs /dev
mount -t sysfs sysfs /sys
mount -t tracefs tracefs /sys/kernel/tracing

# add btrfs support
#insmod /lib/modules/xor.ko
#insmod /lib/modules/zstd_compress.ko
#insmod /lib/modules/libcrc32c.ko
#insmod /lib/modules/raid6_pq.ko
#insmod /lib/modules/btrfs.ko

# mount drives...

# setup networking
ip link set lo up

# setup networking with e1000 card
ifconfig eth0 up
udhcpc -i eth0
rm /etc/resolv.conf

# forward comms
socat TCP-LISTEN:8443,fork,reuseaddr TCP-CONNECT:vmhost:8443 &

# disable printing kern msgs to tty
dmesg -n 1

# give a shell
/bin/sh

# since this is the init program, exiting will cause a panic, poweroff instead
poweroff -f
